### ISSUE TITLE
Development process

### ISSUE THREAD

**Issue by stone** [thorrak/fermentrack#118]
Now when we are in soft-launch (yay!) we will have some installations running, and for every commit to master our users will be asked to upgrade. We could do this until we have got tag support into the upgrade script and even after that following master to always get the last version.

So something like:

- master - latest "stable" (gets tagged when it's time for a release)
- development - bleeding edge (PR's get merged here)
- tags - releases, v0.1, v0.2 and so on..

What do you think?

**Comment by Mikmonken** [comment]
I've got enough spare parts to provide a test rig if you want me to. As you can probably tell though other than flagging the issues I find (at the moment) I'm not going to be a huge help

**Comment by thorrak** [comment]
I thought about this one earlier, and the deferral of the "tagged release only" git integration was actually intentional. For the time being, most of the pull requests are going to be bugfixes, and those need to be rolled out without waiting for a tag. 

My hope is that when we release the v2 milestone the basic functionality will have seen enough use that we wouldn't need 

That said - I agree that for any major refactoring we need to have a branch other than master that is the primary PR destination. Once a feature is ready to release I think it should be pulled to master unless a change isn't backwards compatible (or fully tested).

I've got a "bugfixes" branch locally to try to tackle the issues Mikmonken found - once it's tested I'll push to GitHub & pull to master. For new features (Celery, specifically being the one I'm working on now) I'll probably leave things in their own branch until comfortable that everything works as expected.

**Comment by thorrak** [comment]
Tagging this for release 3 - Once we get to that point, we'll absolutely need to revisit the structure of the branches and see if it makes sense to add a development branch for major changes we wouldn't want to release outside a tagged release.

**Comment by thorrak** [comment]
What I'm thinking here is to avoid tagged releases for the time being, opting instead for a "continuous release" cycle with a "dev" branch that I'm consistently screwing up and a "master" branch that contains "release" quality code. Given this switch, I'm reworking the git integration to allow for selecting between these two.

**Comment by thorrak** [comment]
There's one last fix that needed go go in to finalize this - that fix is now in the tilt_refactor branch and will be included in the next release

**Comment by thorrak** [comment]
This has been in for awhile now. Closing.
