### ISSUE TITLE
Read/display sensor values on "Pin/Sensor Configuration" page

### ISSUE THREAD

**Issue by Mikmonken** [thorrak/fermentrack#119]
it would be useful when installing devices if the temperature was visible on the temp probes (i tend to warm one up when i install so i can see which probe is which in the set up)

Also being able to see what state the relays are i.e inverted or not inverted.

I'd label this as a "would like" if i could work out how to use github.

- [ ] Read/display value for each sensor on the pin/sensor configuration page
- [x] Display inversion state for each assigned pin on the pin/sensor configuration page

**Comment by thorrak** [comment]
Inversion state for each assigned pin should be displayed following the next pull request (hopefully, later tonight). Displaying the value for the sensors is a bit trickier due to the fact that it could potentially exacerbate #108 (the device value is stored as part of the cache). 

Once we're comfortable #108 is squished, we can revisit as this is a feature I expect a number of people would like.
