### ISSUE TITLE
add outside temp to dashboard table

### ISSUE THREAD

**Issue by gezzanet** [thorrak/fermentrack#193]
If you use a 3rd probe for the outside (ambient ) temp, the line shows on the dashboard graph but not in the table on the right

**Comment by thorrak** [comment]
This one is slightly tricky, but only just slightly --

Basically, I don't want to assume that the user has a room temp sensor connected (primarily because I almost never do). To account for this, what I'm thinking is that I'll wrap everything involving room temp in a hidden div, and unhide it if the room temp we pull via the API ends up being something non-blank. 

The downside to this approach is that it means the room temp will visibly "snap in" to the page after the page loads. The upside is that it will be hidden otherwise.

**Comment by thorrak** [comment]
Aaaaand I decided to punt on this one and go the lazy route (for now). The room temp legend will always be visible for now - even when there is no data available.
