### ISSUE TITLE
ABV Calculation/Display on Dashboard

### ISSUE THREAD

**Issue by Mikmonken** [thorrak/fermentrack#247]
it would be useful to display current estimated abv within the log, i.e. taking the highest OG on day one of log, and then subtracting lowest gravity at the point of viewing.

Also a restructure of the web gui, I could try and play with this myself i'd just need a steer in the right direction as to where the code is stored, although i have no idea how I'd go about making the ABV bit work

sorry for the drawing, thought it may help.

![fermentrack](https://user-images.githubusercontent.com/19469569/37827527-c0f227f0-2e8f-11e8-9007-8dc421ff0d7e.png)

**Comment by thorrak** [comment]
The ABV bit would be awesome. Not easy to implement, but awesome - and there’s stuff coming that will make it easier to implement soon. 

The interface for it exists - all the data is being stored in Redis, and it would be easy to add a “SG” high water mark to the data that redis stores. I’m working on Huey integration right now as well, which would allow us to delay or schedule code execution. That would allow us to do something like telling Fermentrack to take a SG reading 1 hour after starting a beer to give the readings time to stabilize. 

At some point over this weekend I’ll co-opt this issue to change it to the ABV dashboard request so we can start tracking it until it gets done. 


On restructuring the dashboard - I would suggest making a separate issue for it (since I’m reusing this issue for the ABV tracking) but here’s what you need to know:

Django uses its own template language which is HTML mixed with custom tags that use curly braces. If you’re comfortable with HTML and the concept of if statements and loops from any other programming language then it’s incredibly easy to understand Django templates (in my opinion). If you want to see one in action, this is the template you want (Temperature Controller Dashboard):

https://github.com/thorrak/fermentrack/blob/master/app/templates/device_dashboard.html

{# #} is a comment and is ignored when generating the HTML to output

{% %} is used for control statements, function calls, etc. You’ll see these for things like if statements and basically anything else that is programmatic. 

{{ }} is used for directly adding the contents of a variable that is being passed to the template from Python. 

Otherwise, it’s all HTML. 

If you want to play by editing this file on your Raspberry Pi, give it a shot!

3 things to know:
1. After making any changes, you may have to relaunch circus to get them to show. See below for instructions
2. If things don’t work out and you want to revert to what’s on GitHub, just do `git reset —hard` while in the Fermentrack directory
3. Once you’re done and like what you see, submit a pull request or otherwise save the data out somewhere - and then do a `git reset —hard` . If you don’t, you may not be able to update from GitHub until you do. 

To relaunch circus:
`sudo su fermentrack`
`cd ~/fermentrack`
`source ~/venv/bin/activate`
`circusctl restart`

If you don’t close the shell, you only need to run the last command each time to restart circus

**Comment by snoop6060** [comment]
I’d also be keen to see the interface redone.  Something that has better compatibility with phones too. I’ve done some work projects with flask with uses the jinja html inheritance framework and programming logic. Looks identical to django so could probably help out. Done lots of python too.

**Comment by thorrak** [comment]
Any help on the interface would be extremely welcome. I am not a designer by any means, and would love to see something better than FlatUI

Sent from my iPhone

On Mar 23, 2018, at 11:01 AM, snoop6060 <notifications@github.com<mailto:notifications@github.com>> wrote:


I’d also be keen to see the interface redone. Something that has better compatibility with phones too. I’ve done some work projects with flask with uses the jinja html inheritance framework and programming logic. Looks identical to django so could probably help out. Done lots of python too.

**Comment by thorrak** [comment]
This was implemented awhile back. Closing.
