### ISSUE TITLE
Profile setup diacytl rest

### ISSUE THREAD

**Issue by atrueresistance** [thorrak/fermentrack#324]
Hello I just installed this to a raspberry pi via the github instructions. It was painless and picked up a legacy brewpi controller used for my fridge. I do have an issue with the fermentation profiles though. 

I want to set up a diacytl rest.

![image](https://user-images.githubusercontent.com/7239809/48215845-c52cd400-e348-11e8-8fe0-1af53d0a5996.png)

but however you import profiles or try setting points it always changes it from high to low temp. 

```
====================================
| Lager, Three Stage               |
| Standard Profile                 |
====================================
| 14d | 54.00 F                    |
| 3d  | 62.00 F                    |
| 30d | 35.00 F                    |
====================================
```

You must be doing some sorting. It would be nice to be able to drag the temps around to get the desired order. 
![image](https://user-images.githubusercontent.com/7239809/48215984-248ae400-e349-11e8-980b-37d5270dc69f.png)

**Comment by thorrak** [comment]
The problem is that the times in the exportable profile in Fermentrack are not how long to stay at a temp, but when that temp should be arrived at following the start of the profile.

What you probably want would be

14d
17d
47d

Sent from my iPhone

On Nov 8, 2018, at 12:27 PM, Frank Wiebenga <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello I just installed this to a raspberry pi via the github instructions. It was painless and picked up a legacy brewpi controller used for my fridge. I do have an issue with the fermentation profiles though.

I want to set up a diacytl rest.

[image]<https://user-images.githubusercontent.com/7239809/48215845-c52cd400-e348-11e8-8fe0-1af53d0a5996.png>

but however you import profiles or try setting points it always changes it from high to low temp.

====================================
| Lager, Three Stage               |
| Standard Profile                 |
====================================
| 14d | 54.00 F                    |
| 3d  | 62.00 F                    |
| 30d | 35.00 F                    |
====================================


You must be doing some sorting. It would be nice to be able to drag the temps around to get the desired order.
[image]<https://user-images.githubusercontent.com/7239809/48215984-248ae400-e349-11e8-980b-37d5270dc69f.png>

**Comment by atrueresistance** [comment]
Ah yes that was it. Thank you.
