### ISSUE TITLE
Unable to locate controller after flashing

### ISSUE THREAD

**Issue by scouseboy999** [thorrak/fermentrack#341]
Hi there,
I have just done a fresh install of fermentrack.  I have successfully flashed a Wemos D1 mini, with the wifi firmware.  When I try to add the controller through the Fermentrack interface using the mDNS option the controller fails to show up.  I have tried a couple of different Wemos and they all produce the same result.  Any help or pointers as to what I might be doing wrong would be appreciated.

Regards

Stuart

**Comment by jangevaare** [comment]
Have you connected directly to each ESP8266 to complete wifi setup before attempting to connect them with Fermentrack?

**Comment by scouseboy999** [comment]
I flashed the controllers through Fermentrack interface.  I have not connected to the subsequently, and I understand what you are saying as I have flashed many esp8266's and normally afterwards the wifi manager runs and allows configuration for the local network.
The question is for me, am I using the correct flashing procedure, should be using the command line for the initial flashing.  Any advice or pointers would be helpful.

**Comment by thorrak** [comment]
You’re using the correct flashing procedure - I have no idea why it’s not then creating the AP to connect to. 

Try running the “wiring test” firmware and see if everything is connected properly. That will additionally reset any settings that may be preventing the AP from launching.

**Comment by scouseboy999** [comment]
Hi thanks for the advice.  could you tell me where to find the "wiring test" firmware.  Thanks

**Comment by thorrak** [comment]
It's an option within Fermentrack. Just go through the flash process like you did to flash the controller, and select the "wiring test" firmware rather than one of the BrewPi firmwares

**Comment by scouseboy999** [comment]
Thanks for the info.  I will have ago and see if it makes the difference

**Comment by meirion** [comment]
I had this issue and drove myself nearly nuts trying to work out what was going on. 

Tried various different Wemos and Nodemcu boards, some were previously in use so known good and then tried it with brand new ones.

What I found that fixed it for me was using the Windows esp flasher tool, and doing a zero reset flash first - writes all zeroes to the esp or something like that.

After doing this, and then using the same flasher tool to flash fermentrack I finally got it working.

Haven't touched it since, still working 6 months on thank goodness.

**Comment by thorrak** [comment]
If @meirion 's method turns out to be what is required to make this work, I'll add support for this flash mode ([erase_flash](https://github.com/espressif/esptool#erase-flash-erase_flash--erase-region)) to Fermentrack as a button at the bottom or something.

The other thing I should mention though -- The issue here may be that mDNS isn't supported by your router. If you continue to have issues, try connecting via the IP address of your controller. If _that_ doesn't work, try the "BrewPi /w WiFi - BETA FIRMWARE" option in Fermentrack.

**Comment by scouseboy999** [comment]
I would like to thank you all for your constructive comments.  I have spent most of the day trying all the suggestions and I am still no further forward.  I do not seem to get able a stable setup on wifi.  I should point out that I am using the thorrak break out board which is super.  The ironic thing is that I had a working setup using bread boards, so I thought I would move everything onto the proper breakout boards and thats when the problems started.  I have order some more wemos and will try again when they arrive.  A couple of  questions,  What is the function of J1 on the board, if use the serial option I am not able to create more that one serial controller connection.
Once again thanks.

**Comment by scouseboy999** [comment]
I seem to have had some success.  Re flashed both wemos controllers with wifi firmware.  Both came up in WiFi manager mode allowing me to configure wifi for my network.  Added the controllers via mDNS , script started then configured the pins for heat, cool and temp. So far so good.  Installed the controllers onto the break out board, powered on with 5v the script will not start.  I am finding that I have to connect 5v to the micro usb on the wemos to make them work.  Is this correct?  If I remove the usb power off the wemos they stop working.  The only way to start them again is to remove them from the board and reset them, once working re-install them.  I am a little puzzled.

**Comment by thorrak** [comment]
Did you get this working?

**Comment by scouseboy999** [comment]
I have indeed, but as mentioned in a previous post it appears that I have to have the 5v connected to your breakout board and also to the Wemos via the usb port.  Without this the board do not boot up.  Is the correct?

**Comment by thorrak** [comment]
That shouldn’t be the case - the 5v connector on my PCB should connect to the 5v pin on your D1 mini which should in turn power the controller.
