### ISSUE TITLE
Cannot add Tilt with connectiontype Bluetooth

### ISSUE THREAD

**Issue by wpeterw** [thorrak/fermentrack#376]
Trying to add a Tilt with BT:

Error adding sensor - See below for details

With no details or logging. Is BT supported yet ?

**Comment by TigNewton** [comment]
Bluetooth is supported and functional. 

This sounds similar to a problem I am having (https://www.homebrewtalk.com/forum/threads/fermentrack-fermentation-monitoring-brewpi-www-replacement-for-raspberry-pi.649303/page-21#post-8689272).

Scroll down and look at the "Tiltbridge" field and see if it says "Required entry".

**Comment by vanosg** [comment]
Can you try again with the most recent commits? It was discovered that Buster did not include some bluetooth libs by default. I have no idea if this is related to your issue, but its worth another try now perhaps

**Comment by TigNewton** [comment]
Vanosg,

That's not my problem. I was able to install two Tilts without issue. Both were functioning as expected. Maybe my problem is something different. I will open a new issue.

**Comment by thorrak** [comment]
This should be fixed with the latest changes, but it will require manual intervention for anyone who has a preexisting install. To quote my post on HBT about how to make everything work:

Update on the Bluetooth issues under Buster

Apparently, previous versions of Raspbian included libbluetooth-dev by default which is a prerequisite for installing the pybluez library which is used by Fermentrack to communicate with bluetooth devices. For Fermentrack to work under Buster, that library needs to be installed.

I’ve added this to the install script so future installations should work fine, but for completed installs you will need to install libbluetooth-dev manually (and then trigger a forced update in Fermentrack to get pybluez installed). Here’s how to do that:

Log into your Raspberry Pi via ssh
Run “sudo apt-get install libbluetooth-dev”
Run “sudo su fermentrack”
Run “source ~/venv/bin/activate”
Run “cd ~/fermentrack”
Run “pip install -r requirements.txt”

This should result in pybluez being installed without any error messages
