### ISSUE TITLE
Tiltbridge not logging due to temperature conversion issue

### ISSUE THREAD

**Issue by bgradid** [thorrak/fermentrack#411]
It looks like there might be an issue with using a tiltbridge and fermentrack in celsius

Not getting any data from my tiltbridge into fermentrack even though the tiltbridge itself picks up data just fine. Looks like fermentrack is logging a bunch of lines like this whenever the tiltbridge pushes an update

ERROR:app.models:BeerLogPoint.enrich_gravity_data called with unsupported temp format None

I'm guessing this is because I'm in Celsius and I think the Tiltbridge is pushing updates in fahrenheit?

**Comment by thorrak** [comment]
I spent some time working through this one, and while there was a bug with the actual _error message_ you were getting I think the problem here was actually that the TiltBridge hadn't logged any data points before the temperature controller went looking for them.

Regardless, I tweaked the code slightly so that it will (hopefully) generate a logable error if this happens again.
