### ISSUE TITLE
Reset uno board form Fermentrack

### ISSUE THREAD

**Issue by p0ttsworth** [thorrak/fermentrack#447]
During my first batch, Fermentrack lost signal from the 2 temp sensors after a couple of days.

Pressing the reset button on the Uno fixed the problem - is there a way a Uno reset command could be included within fermentrack, so you can remotely reset the board without having to physically access it?

**Comment by lbussy** [comment]
If you restart the script (at least in BrewPi) the board will restart.

**Comment by p0ttsworth** [comment]
Thanks

What's the best way of restarting the script?  Can you do it via the web interface from another computer, or do you need to VNC / SSH into the pi?

Will you lose the ongoing log if you restart the script, or can it carry on logging?

**Comment by lbussy** [comment]
I'm not actually a user of Fermentrack - but I am sure the script is there in a form.  Perhaps someone else will be able to help with that.

Restarting the script does not impact logging.  Since the controller is restarting anyway there will be a blip in controlling because of the normal "wait for heat/cool" but that's about it.

The nuclear option is rebooting the Pi. :)

**Comment by thorrak** [comment]
I don't actually have a flashed Uno to test with, but I definitely have the functionality present in the firmware for the ESP port. I'll add a button to the controller settings page to trigger a restart.

**Comment by p0ttsworth** [comment]
Awesome - thanks 

Regards

Rich Potter
