### ISSUE TITLE
Is there a way to display the data on Home Assistant using mqtt or json? Are you aware of anyone doing this?

### ISSUE THREAD

**Issue by blazem** [thorrak/fermentrack#460]

**Comment by lauofdoom** [comment]
I'm posting the data from Fermentrack to NodeRed via a websocket then distributing to MQTT and HA sensors that way. Happy to share the config and flows if you are interested.

**Comment by blazem** [comment]
> I'm posting the data from Fermentrack to NodeRed via a websocket then distributing to MQTT and HA sensors that way. Happy to share the config and flows if you are interested.

yes please i would really like to see that - as well as a snip of your data on the HA dash?

**Comment by markcollar** [comment]
I'd like to see it also, if you don't mind.

**Comment by uSlackr** [comment]
I’m just getting into HA myself and would like to see this integration. Maybe we can dig up the docs for this.

\\\\ Greg
________________________________

**Comment by mp-se** [comment]
What information/data do you want to have? 

An option could be to use the push target functionallity to send data via http and then convert it to mqtt or add mqtt as a pushtarget... I'm also using HA and this would be a nice feature to have.

**Comment by mp-se** [comment]
I belive it should be possible to use nodered with standard push target to convert the http request to mqtt for use in home assistant. Will give it a try hopefully this weekend

**Comment by lauofdoom** [comment]
Hey Sorry guys, completely missed your requests for this info.
Have a look here:
[Fermentrack HA Sync](https://github.com/lauofdoom/fermentrack_ha_sync)
Thsi is my nodered flow for this - syncs push data from fermentrack inot home assistant via ha sensor nodes, and alos brewfather via the web API.
Hope it helps.

Cheers

**Comment by lbussy** [comment]
I'm trying to picture this and/or understand why I've never wanted it.  I want EVERY gadget, so it must mean I just need to know more.  How would I know I've been missing this all my life?  :)

**Comment by uSlackr** [comment]
I’ve not looked at the offered nodered integration so bear with me. I’d love to see the beer temp, gravity and mode settings as a minimum

\\\\ Greg
________________________________

**Comment by mp-se** [comment]
I have tested and can confirm that its possible to use the generic http push function to send data to node red and then update sensors in home assistant. I've used the HTTP IN in combination with HA_ENTITY to make it work. It will require some work to extract the values of interest. Here is an example of the payload from fermentrack so you can see what options are available in the HTTP post message; (I'm missing the beer_temp in this version since I dont have that configured for my keezer).

{"api_key": "sdfssfsdf", "version": "1.0", "brewpi_devices": [{"name": "keezer", "internal_id": 1, "temp_format": "C", "control_mode": "f", "fridge_temp": 4.06}], "gravity_sensors": [{"name": "iSpindel1", "internal_id": 1, "sensor_type": "ispindel", "gravity": 1.026436234683, "temp": 25.2, "temp_format": "C"}]}

**Comment by mp-se** [comment]
Here is a little more detailed description of my node-red flow for importing to homeassistant. 

First I setup a Pushtarget in fermentrack that consisted of my Fermentration Fridge, Keezer and iSpindel. The important thing is the URL which needs to contain the full path to the node-red instance, in my case; http://192.168.4.100:1880/fermentrack (note that the port number field can be ignored since its not used). Port 1880 is the standard port for node-red. 

My node-red flow looks like this and I will assume that you have a working connection towards your home assistant installation and the needed add-on is installed. 

![image](https://user-images.githubusercontent.com/51722613/101382791-a814b780-38b8-11eb-8073-3c884dc6ff23.png)

On the HTTP receive node I select MODE: POST and URL: /fermentrack 
On the JSON node select "always convert json to object"
On the HTTP response add code 200 (OK) otherwise the connection will not be closed.

On the HA ENTITY nodes use the following;

NAME; set the name that will show up in HA
SERVER; select your HA server
TYPE; Sensor
STATE; [msg] payload.brewpi_devices[1].fridge_temp

if you add a debug from the json conversion you can see what attribues are available in your system. other variable that I extract... you can add as many HA entities you want and extract the data you want. 

payload.brewpi_devices[0].fridge_temp (first device in my list, my case Keezer)
payload.brewpi_devices[1].fridge_temp (second device in my list, my Fridge, fridge probe)
payload.brewpi_devices[1].beer_temp (second device in my list, my Fridge, beer temp probe)
payload.gravity_sensors[0].gravity (Gravity value from the first sensor) 
payload.gravity_sensors[0].temp (Temp probe on my ispindle)

**Comment by mp-se** [comment]
@thorrak I believe you can close this one, there is no need to add any new push targets for fermentrack at this point.

**Comment by uSlackr** [comment]
@thorrak could you reuse the code from tiltbridge to add mqtt  support here?  
Also, have you considered adding a "by me a coffee/beer link"  Buying stickers and magnets doesn't seem enough :-)

**Comment by thorrak** [comment]
> @thorrak could you reuse the code from tiltbridge to add mqtt support here? Also, have you considered adding a "by me a coffee/beer link" Buying stickers and magnets doesn't seem enough :-)

If the support is built into the controller itself, then yes. Unfortunately, though, building this into Fermentrack would require being built from scratch. This isn't something I'm likely to build out, unfortunately, so I'm closing this issue for now.

**Comment by uSlackr** [comment]
I'm pretty sure this can be done with a HA webhoook,  I plan to look into this and will pass along the how-to when done.
