### ISSUE TITLE
Can't remove data points on ferm profile

### ISSUE THREAD

**Issue by vanosg** [thorrak/fermentrack#474]
It looks like you can add data points to a fermentation profile, but not delete them- if the wrong point is added (or you just want to modify the profile based on the progress of a brew), you have to delete the profile and start from scratch (via the UI, at least). It would be helpful to delete set points from the ferm profile screen.

**Comment by Garzlok** [comment]
Well, though you cant delete a ferm point through the fermentation profile edit url. It is possible to delete a ferm profile point through the Django Admin Panel, and you're not relegated to starting a profile from scratch.

**Comment by thorrak** [comment]
Hmm. That's strange - I have the ability to delete data points just fine:

<img width="1214" alt="Screen Shot 2020-05-25 at 10 20 37 AM" src="https://user-images.githubusercontent.com/2457900/82821130-8484a500-9e71-11ea-8a28-9d44cd94d1a8.png">

Did you have the fermentation profile actively assigned to a currently-fermenting beer? If so, editing is disabled by this check:
https://github.com/thorrak/fermentrack/blob/bc305c302ae0642bcefda9ee4b17e6f8dc5da1d6/app/models.py#L1497

That said - there actually is a bug here - it's just that the bug is that the "Add Setpoint" form isn't disabled (and apparently the "add setpoint" form processor doesn't check if the profile is editable).

**Comment by Garzlok** [comment]
😂well...I never realized those Red X’s did something....that makes that process easier!😂

**Comment by vanosg** [comment]
OK, that was it- it was assigned to a current brew. For what my opinion is worth, I'd like the option to edit the profile while brewing and apply it- it helps me dial-in a new profile to how the yeast is doing during my first time with it during a brew.

**Comment by thorrak** [comment]
I thought about it, and debated it a bit, and I'm going to add the ability to edit assigned profiles - just with a giant warning message at the top of the page that the profile is currently active/assigned. 

I'll need to recheck the BrewPi-script logic to make sure that I have something in place to reload the profile periodically - but that should probably be in there regardless to prevent errors from caching.

**Comment by vanosg** [comment]
I love it, and the banner is a great compromise in there- best of both worlds! Thanks for the consideration
