### ISSUE TITLE
Upgrade broke the UI

### ISSUE THREAD

**Issue by vanosg** [thorrak/fermentrack#481]
Ran the upgrade option via the web application. I saw it get as far as 'refreshing python environment' or something like that, but now it gives me nginx 'Bad Gateway' errors when trying to navigate to the webpage. 

I see this in var/log/nginx/error.log:
```2020/06/07 15:22:59 [error] 602#602: *115657 upstream timed out (110: Connection timed out) while reading response header from upstream, client: ::ffff:192.168.1.7, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8123/", host: "192.168.1.26"```

What else can I provide?

**Comment by mp-se** [comment]
I had a similar issue connected to failure upgrading to django 3. Check if all the processes are running using circusctrl. When the fermentrack process was down i got this error

**Comment by thorrak** [comment]
@vanosg If you're running on Stretch, then it's probably because Stretch doesn't have Python 3.7 by default. The "fix_environment" script I have posted _should_ fix that - or you can upgrade to Buster. 

I'm mildly annoyed that Django doesn't have longer support windows for older versions of Python, but I'm hoping that the upgrade to Django 3.0 buys me another couple of years before I have to jump through these hoops again.

**Comment by vanosg** [comment]
Cool - it may be worth adjusting something in the upgrade process to check or otherwise auto fix or warn/notify (yeah, hard to do via the web UI, but still) for this issue- other users might hit that upgrade button and then it all just breaks. Just my two cents, but this turns what is generally expected to be an automatic process into something that requires manual intervention, with no clear info presented via the UI upgrade process that some systems may have issues, or may need to run something, etc etc. my hope would be to prevent people from needing to Google or sort through the issues section here to find the answer

Running the fix-environment thing now, I'll let you know if that doesn't fix it (yes, I'm on stretch).

**Comment by vanosg** [comment]
Also, just happened to notice this in the scroll:
```
Python/_warnings.c: In function ‘do_warn’:
./Include/object.h:801:12: warning: ‘filename’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if (_Py_DEC_REFTOTAL  _Py_REF_DEBUG_COMMA       \
            ^
Python/_warnings.c:842:15: note: ‘filename’ was declared here
     PyObject *filename, *module, *registry, *res;
               ^~~~~~~~
```

**Comment by thorrak** [comment]
I tried, I just did it way too late ;) 

https://github.com/thorrak/fermentrack/commit/b8fd21aeea9e7b1d5695648c10e7a026cafdcc49

If I was a smarter man, I'd make it so that the upgrade process pulls something from fermentrack.com (or something) which contains the system requirements it should check against. Possibly something to add later. 



> Also, just happened to notice this in the scroll:
> 
> ```
> Python/_warnings.c: In function ‘do_warn’:
> ./Include/object.h:801:12: warning: ‘filename’ may be used uninitialized in this function [-Wmaybe-uninitialized]
>          if (_Py_DEC_REFTOTAL  _Py_REF_DEBUG_COMMA       \
>             ^
> Python/_warnings.c:842:15: note: ‘filename’ was declared here
>      PyObject *filename, *module, *registry, *res;
>                ^~~~~~~~
> ```

Yell at the Python devs. :)
