### ISSUE TITLE
10 x Blown PWM D6 pin on Wemos D1 Mini boards with Firmware 0.11

### ISSUE THREAD

**Issue by simonboydfoley1** [thorrak/fermentrack#486]
I have had 2 months of utter  hell getting this project working.
I have killed 10 boards with this firmware (including originals and clones)
I install and configure the unit fine via guided flash over USB with wifi .

I can see the OneWire initialization by the firmware on my scope and register the line and temperature sensors (beer, room, chamber)

I use the device for a few hours sometimes I will get 24hrs bed in then set up a beer to brew but find the firmware no longer reports any of the temperature probes.

I have tried reflashing, resetting eprom etc etc ... But when I scope the oneWire data pin D6  the firmware host refuses to send any initialization sequence ... I get nothing ... the pin stays high all through the power up sequence.

I have to flash a brand new controller board to pick up the temp probes again 
... But the  same thing happens again and again it's like OneWire only works on the first installation and config ...after that it breaks.

I have checked the voltage and it's been 4.7v to 5.1v on the USB micro port (fed from a buck converter from a 12v DC supply)
I am also pulling the D6 pin high (about 4.1v) with a 4.7k resistor.
I'm running room, chamber and beer probes.

I don't know what's happening to that D6 pin and why the firmware is not getting the initialization sequence out on the wire.

I'm pulling my hair out here ....10 boards bricked. ....

Any ideas what's happening ?
I'm trying to eliminate the firmware.

**Comment by thorrak** [comment]
What firmware are you using? https://github.com/thorrak/brewpi-esp8266 ?

**Comment by thorrak** [comment]
Also, what PCB design are you using?

Have you tried different temperature sensors?

**Comment by lalo-uy** [comment]
Esp is a 3,3V device. If you put the 4k7 pull up to 5V it may break the D6
pin when the bus is idle.
DS18B20 may be powered with 5V , but the data line must be pulled up to 3.3V

**Comment by thorrak** [comment]
I'm pretty sure @lalo-uy hit the nail on the head.

**Comment by simonboydfoley** [comment]
Thanks for the help guys,
  I am using the brewpi-esp8266.v0.11.wifi.bin.
The boards I am using are from AZDelivery clone of Wemos D1 Mini, but I have also used a Original Wemos D1 Mini Pro, and wemos D1 Mini Develop board and I have ordered some NodeMCU Amica original's which I have not tried yet.
Most of the failures have been with the clones and sometimes they last less than 30min after flashing and configuring.,

I have started to use ESP8266Flasher.exe to flash instead of the fermentrack flasher to elimante this.
I have also started to flash a blank firmware and  then the image to eliminate any residual settings.
If this is firmware I shoudl be able to prove it by removering the unit with a complete firmware reset (I am doing this now).

As for the pull up voltage ... I will double check now, but I was powering the Tempriture Probes (2 different DS18B20 manufactures) from the 5v and ground rail on the D1 Mini (the specs say they need 5v). In reality the 5v supply via the USB Mini port and the power chip on the microcontroller meant that the 5v pin was proving about 4v. All the documentation said to bring the D6 Pin hign by using a 4.7K resistor between the + and Data pin on the tempriture probe which I did.

I then suspected that the problem was the lack of true 5v to the temprituire probes so I powered the  tempriture probes from a dedicated 5v rail that I was using to power teh D1 Mini Boards and brought the pin high from that 5v source.

I will double check the voltages and it may be I need to bring the pin D6 pin high from the 3.3v rail on the D1 Mini.
I will get back to you 

again thanks fro your feedback

**Comment by simonboydfoley** [comment]
Just checked the voltage ... I misread my scope contrast was low and i misread it the High Voltage on D6 is approx 3.3v so its not that :-(

I also can not recover the firmware on any of the blown units .,.... so It looks like its a physical problem.

I do notice that the units all are really really hot on the esp8266 chip .... I have put a heat sink on it and its too hot to touch.
This happens even without any pins connected so its not a short.
It maybe heat thats destroying the chip's ... but I check the current and its pulling 0.262A which is what people suggest is normal.

I'll kick off another new unit and see if I can spot whats stopping the OneWire initialisation on D6 and killing the units.

#stillstumped
![FriedWemos](https://user-images.githubusercontent.com/13658441/87840731-79625a00-c8a1-11ea-8695-a1f9430264fc.jpg)

**Comment by simonboydfoley** [comment]
Well thats interesting. With a brand new unit .... its pulling in half the current !
I have only configured the the chamber and heater relays.
I will now add the tempriture probes one by one and see if I can spot what triggers the doubling of current,

![NewD1Clone](https://user-images.githubusercontent.com/13658441/87841076-0e198780-c8a3-11ea-9a83-851c44c74380.jpg)

**Comment by simonboydfoley** [comment]
Right I am getting closer.
On the blown units ..... the voltage on D6 Pin is 3.2v.
On a brand new unit the voltage *is* 5v  on the D6 pin ..... I was not wrong reading my osciliscope, its just that after the device fails the voltage on the pin drops to 3.2v

The 4A2D Voltage regulator chip still seems to be providing 5v and the 3,3v rail is still working as well, so seeing as Im bringing the pin hig from the 5v rail still, perhaps something has blown in the esp8266 chip in serial with the D6 Pin reducing the circuit resistance and causing the currnt to double and the heat to generate,

I'll bring the D6 Pin high fro the 3.3v rail on the D1 Mini Clone and see if it lasts any longer than before.

#fingerscrossed

**Comment by simonboydfoley1** [comment]
Yup it's been stable now for 24hrs ....longest time ever ...so root cause was using 5v to bring D6 high for one wre.
I'll reach out to the guy that wrote the guide and warn him of the issue
