### ISSUE TITLE
Backup directories

### ISSUE THREAD

**Issue by akang6** [thorrak/fermentrack#499]
I  have fermentrack running beautifully but I want to make sure that everything is backed up but didn't see anything in the documentation about what directories need to be backed up so that I could migrate/restore if something happens.

Thanks

**Comment by vanosg** [comment]
I'm not an authority, but this should be a good start if no one else chimes in:

1) The conservative answer would be to backup the /home/fermentrack directory- that should have everything non-default in it
2) If that isn't sufficient, then the /home/fermentrack/venv dir can probably be skipped (it should be reinstalled on a new install), but it certainly wouldn't hurt to keep it. All in all, the filesize of /home/fermentrack is roughly 225MB, about half of that is the venv dir. 
3) If that still isn't sufficient, (and this is where I may miss a crucial file, which is why I wouldn't go past #2 in terms of backups), you can get really granular and keep the ...../log ...../data and db.sqlite3 files.

Hope that helps get you started

**Comment by mp-se** [comment]
You will need to backup 2 things in the fermentrack directory;

/home/fermentrack/fermentrack/data- here is where your brew-logs are stored. 
/home/fermentrack/fermentrack/db.sqllite3 - the main database file.

Everything else can be re-installed via the installation scripts and then restore the files/folders above and you should be fine.

**Comment by thorrak** [comment]
You also need your `fermentrack_django/secretsettings.py` file in addition to the two that @mp-se mentioned. With those three things (secretsettings, data folder, db.sqlite3) you should be good to go!
