### ISSUE TITLE
PID Tweak to avoid cooling overshoot

### ISSUE THREAD

**Issue by dannyshaw** [thorrak/fermentrack#506]
Is there a setting to change so that when the temperature is declining on it's own, it waits a little longer rather than kicking in the condenser and overshooting the drop in temperature (and thus requiring a longer heat cycle)? 

None of the control settings seem to intuitively match up with what I want to achieve here.
 
![image](https://user-images.githubusercontent.com/603175/96389256-3a260b00-11fa-11eb-83a1-436c37b4d840.png)

**Comment by cpompermaier** [comment]
I also see this difficulty in my setup. Now in the winter the exterior temperature where I have the refrigerator is about 5 to 8C. It would be great if we could just disable the Cooling feature based on the ambient temperature. The same is valid for the summer when the ambient is higher than the beer fermenting.

**Comment by lbussy** [comment]
The beer temp is still within a couple of tenths of a degree.  I fail to see the issue.

**Comment by dannyshaw** [comment]
Efficiency I guess. Not a huge issue, was just wondering if there were configuration options. 

Kinda see it like having the heating on in the house and turning on the AC every now and then to control temp rather than adjust the heater.

**Comment by lbussy** [comment]
In commercial controls, you vary the input based on the delta.  Here, the refrigerators run at one setting and the heater is one wattage.  There's not currently a good way to effect this change so that it's right all the time.  You could change your heat bulb to a lower wattage in the spring and fall maybe?  PWM in the newer controllers helped, but it was really a solution looking for a problem.

The controller firmware is a port of the original Arduino Uno code.  Yes, it could be expanded to add another control point (room sensor or outside temp) but what real benefit do we get out of potentially breaking code that has been working for so many years without a bug?

This is Thorrak's code (and this is the wrong repo), but I'm just pointing out you may be letting the perfect be the enemy of the good.  I'm not the guy you need to convince.

**Comment by cpompermaier** [comment]
My point was that it makes no sense to heat the beer and then soon start cooling the refrigerator because of a small overshoot. If the ambient temperature is lower than the beer, it is natural that the temperature will drop again, considering that the overshoot is within tolerable values. That will help conserving the compressor who doesn't need to be called so often. I managed to improve mine by tweaking the PID gains. I agree with you @lbussy that the perfect is the enemy of the good. Difficult to find a proper balance sometimes :)

**Comment by dannyshaw** [comment]
Not trying to convince anyone of anything, just asking if there were settings Im not aware of. Cheers all!

**Comment by lbussy** [comment]
Don't take my saltiness as a conversation killer.  Imagine me saying it with a smile, in a bar, over a nice beer.

Without that last input (ambient/room/outside) there's no real way to do what you are saying.  Adding it could introduce unintended consequences to a system that is really very, very effective.  Seems risky to me but I'm just a dude in a bar.

**Comment by uSlackr** [comment]
Lee, I think the point is - fermentrack (like brewpi before it and brewpi-remix) were designed to control temps within a very tight band.  Changing that would defeat its purpose.   There are other solutions that aren't designed for this. 

And, FWIW, I don't connect my heat belt during the summer as it seems pointless.  
(I would also say - there is likely no beer related reason to control temp this closely, but we all do anyway)

**Comment by dannyshaw** [comment]
I'm pretty naive of how the algorithm works, in my mind there was the idea that it would be able to see that the last n attempts to heat to x resulted in actually heating to x + y, therefore change the target to

**Comment by lbussy** [comment]
PID is really pretty cool and does allow for adjustments like that.  It's smart for a dumb formula if that makes sense.
