### ISSUE TITLE
Theme question

### ISSUE THREAD

**Issue by uSlackr** [thorrak/fermentrack#508]
The mobile screens I see when viewing the Tilt dashboard is different in layout from the temp controller view. Is it possible to get the more concise view for the controller? 
![image](https://user-images.githubusercontent.com/25751399/97121141-68bc4e00-16f2-11eb-946d-62bdec5ec80d.png)
![image](https://user-images.githubusercontent.com/25751399/97121145-6ce86b80-16f2-11eb-882c-70ac5c33e15c.png)

**Comment by uSlackr** [comment]
Perhaps the larger question is how is the layout controlled?

**Comment by thorrak** [comment]
Hey there -- Apologies for the substantial delay in responding to this. The layout is controlled through [template files](https://github.com/thorrak/fermentrack/blob/master/app/templates/device_dashboard.html) which Django renders server-side to show what you see in your screenshots above. To change the layout/fix issues, generally you would need to update the template file(s) for the relevant templates.

Unfortunately, as you have noticed, I am not particularly skilled when it comes to front-end design (Hence Issue #248 !) and originally built Fermentrack as a desktop-first application which resulted in the issues you are seeing. In the years since I made this decision, new "developer friendly" user interface libraries have been released, and I am currently in the process of rebuilding Fermentrack's UI to leverage mobile-first concepts. This change is going to take several months, however, and thus for now we're stuck with what we've got.

If you're interested in tracking against the redesign, I recommend watching/following issue #248 as I'll post more information there as it becomes available.
