### ISSUE TITLE
Minimum maximum times

### ISSUE THREAD

**Issue by gieljnssns** [thorrak/fermentrack#584]
Is there a way to specify the minimum and maximum heating and cooling time?

**Comment by uSlackr** [comment]
I don’t believe so.  What are you trying to accomplish


\\Greg

**Comment by gieljnssns** [comment]
The heating I'm using originally had a thermocouple as protection, but my chamber doesn't reach the setpoint. 
So I removed the thermocouple, now I want to accomplish that my heater heats for a maximum of time, then rests for x time and heats again.

**Comment by thorrak** [comment]
This is now configurable via the web interface that was released as part of [v15 of BrewPi-ESP8266](https://github.com/thorrak/brewpi-esp8266/releases/tag/v15). 

Since this is something that is intended for advanced users (given that it can cause hardware damage if misconfigured!) I'm not currently planning on adding support to configure this as part of Fermentrack. If anyone feels strongly otherwise, feel free to make your case and we can discuss.
