### ISSUE TITLE
Cooling duty started before beer

### ISSUE THREAD

**Issue by uSlackr** [thorrak/fermentrack#614]
I just started the beer in the past 10 minutes, but the "LCD panel" shows it's been cooling for 2+ hours.  I'm certain I turned off the controller after the last beer. 
![image](https://user-images.githubusercontent.com/25751399/111881668-f80b1c00-8987-11eb-8ea8-f8011350b12d.png)

Running latest Dev branch from 3/12.

\\Greg

**Comment by thorrak** [comment]
Ah, hm. I have no idea.

The "Cooling for" text is read off the controller, so that would indicate the _controller_ thought it was set to cool for 2 hours.

**Comment by uSlackr** [comment]
Weird.

\\\\ Greg
________________________________

**Comment by thorrak** [comment]
Interestingly enough, @lbussy ran into a similar issue where he was seeing a time improperly printed over the temperature control text that is supposed to appear when the controller is off:

![image](https://user-images.githubusercontent.com/2457900/112158692-c9c35180-8bbe-11eb-8207-8577c0c5c0bb.png)

There appears to be a strange condition that can be triggered when the mode is set to "Off" where the text associated with the "off" mode doesn't get properly applied resulting in strangeness on the LCD. The bug is pretty straightforward - a missing `else` - but as the impact is purely cosmetic, I'm going to leave it queued up for a future release.

I raised the issue on the BrewPi-ESP8266 repo here to track against:
https://github.com/thorrak/brewpi-esp8266/issues/61
