### ISSUE TITLE
docker install failing

### ISSUE THREAD

**Issue by Kickbut101** [thorrak/fermentrack#694]
Docker v 20.10.18 on debian linux
```
root@docker:~# docker run jdbeeler/fermentrack
/entrypoint: line 9: POSTGRES_USER: unbound variable
```

btw, the wiki page has this:
`curl -L install.fermentrack.com | bash`

But the landing page on github says this:
`curl -L install.fermentrack.com | sudo bash`

**Comment by thorrak** [comment]
I see you are running docker run jdbeeler/Fermentrack/endpoint — generally I would expect you would use the docker compose file (and docker compose) instead of running Fermentrack directly. 

The issue is that all the passwords are in a .env file that gets loaded by docker compose in order to keep the database credentials somewhere that won’t get overwritten and isn’t part of the repo. You can replicate this behavior with docker run I think if you want to separate out the images (and host the other services yourself manually) but you would need to do a slight bit of digging. Take a look at the env directory in Fermentrack Tools as well as the compose file that is there.

**Comment by Kickbut101** [comment]
I'll do it however is the "right" way. I did initially try running just the install script but that also gave errors so I just switched to trying to use a docker and still was hit with problems.

**Comment by thorrak** [comment]
Not sure what errors you're encountering with the original install script, but I'm happy to try to help with those if you post them. 

As I mentioned, you can use the Fermentrack image directly from docker if you want, but you need to specify an env file using the `--env` flag that has the [configuration options Fermentrack expects](https://github.com/thorrak/fermentrack/blob/master/.envs/.prod-sample/.django) if you want to go that route.

**Comment by thorrak** [comment]
I completed a handful of installations this weekend, so I'm assuming this is resolved. Please feel free to reopen if you are continuing to have issues.
