### ISSUE TITLE
Cannot set temperature below zero

### ISSUE THREAD

**Issue by jalim** [thorrak/fermentrack#742]
I've been setting up a new ESP32 controller to replace an old D1 Mini and after getting it installed and trying to setup the device, I've noticed I cannot set a minimum temperature less than zero.  It seems that whenever I set a negative value, the actual value set becomes the opposite value (-10 becomes 10, -5 becomes 5, etc).

In my case I want to be able to cold crash with the freezer hitting sub zero temperatures during the process.  I may be imagining things but I was sure I was able to do this on the previous build.

**Comment by thorrak** [comment]
Thank you for reporting this! Interestingly, I dont know how long this bug has been out there but I stumbled across it myself on this side by accident two days ago when trying to investigate a different issue for someone on HomeBrewTalk. 

The issue is entirely in the [display on the device](https://github.com/thorrak/brewpi-esp8266/issues/91) - not in Fermentrack. If you change the device from Celsius to Fahrenheit you will see that it will drop below 32 as expected. Make sure that your control constants are set such that the minimum temperature is lower than 0 as well to make sure you can chill below 0 if that is what you would like to do.

**Comment by jalim** [comment]
Ah interesting, I was trying to set edit the control constant minimum temperature and after saving and then returning to the setting page it would return to the absolute value and loose the negative value.  If I get time I'll have a look through the flow of setting the control constant and see if there's anything there.

**Comment by jalim** [comment]
It seems everything is being reported by the device in absolute values, even the log has interesting results with the temperature hitting zero and immediately 'climbing' at the same rate as it was falling:
![image](https://github.com/thorrak/fermentrack/assets/6856386/9f61b519-43f8-4529-8d3c-4e8057f13fad)

**Comment by jalim** [comment]
I'll close this issue here as it's not fermentrack but rather brewpi-ESP that has the [issue](https://github.com/thorrak/brewpi-esp8266/issues/91).
